
services:
  minecraft:
    image: evgeniyfimushkin/mine
    build: .
    container_name: mine-server
    ports:
      - "25565:25565"
      - "80:8080"
    volumes:
       - ./server.properties:/minecraft/server.properties:z
       - ./world:/minecraft/world:z
    environment:
      - MEMORY_MAX=8G
      - MEMORY_MIN=2G
      - TZ=Asia/Novosibirsk
    stdin_open: true
    tty: true
    restart: always
